services:
  db:
    image: mysql:${MYSQL_VER:-8.4}
    container_name: mysql_badminton
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_TCP_PORT: 3306
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - badminton_db_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - badminton-network
    restart: unless-stopped
    command:
      - --bind-address=0.0.0.0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=1000
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:${REDIS_VER}
    container_name: redis_badminton
    ports:
      - "${REDIS_PORT:-6380}:6379"
    environment:
      REDIS_PASSWORD: ${PASSWORD}
      REDIS_DATABASES: ${REDIS_DB_NAME}
    volumes:
      - badminton_redis_data:/data
    networks:
      - badminton-network
    restart: unless-stopped
    command:
      - redis-server
      - --requirepass ${PASSWORD}
      - --appendonly yes

networks:
  badminton-network:
    driver: bridge
    name: badminton-network

volumes:
  badminton_db_data:
  badminton_redis_data:
